name: tugasakhir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  flutter_toggle_tab: ^1.2.0
  table_calendar: ^3.0.6
  intl: ^0.17.0
  excel: 
    git: 
      url: https://github.com/justkawal/excel.git
      ref: null-safety
  firebase_storage: ^10.3.4
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  better_open_file: ^3.6.3
  timeago: ^3.2.2
  fl_chart: ^0.55.1
  pdf: ^3.8.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

